In [1]:
import numpy as np
import pandas as pd

# Handling Missing Data

### Filtering Out Missing Data

In [2]:
from numpy import nan as NA

data = pd.Series([1, NA, 3.5, NA, 7])

data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [3]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [4]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])

cleaned = data.dropna()

In [5]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [6]:
cleaned

0    1    2
0  1.0  6.5  3.0

Passing how='all' will only drows rows that are all NA:

In [7]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

To drop columns in the same way, pass axis=1:

In [8]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [9]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

You can indicate a threshold using the thresh argument:

In [11]:
data.dropna(thresh=2)

0    1    2   4
0  1.0  6.5  3.0 NaN
3  NaN  6.5  3.0 NaN

### Filling In Missing Data

In [14]:
df = pd.DataFrame(np.random.randn(7, 3))

df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0 -1.253882       NaN       NaN
1  1.244064       NaN       NaN
2 -0.190684       NaN -0.334609
3  0.338836       NaN -0.573983
4 -0.667814 -0.257970 -0.049162
5 -0.096871 -0.034499  0.013993
6 -0.701870 -0.472082 -1.361445

In [15]:
df.fillna(0)

0         1         2
0 -1.253882  0.000000  0.000000
1  1.244064  0.000000  0.000000
2 -0.190684  0.000000 -0.334609
3  0.338836  0.000000 -0.573983
4 -0.667814 -0.257970 -0.049162
5 -0.096871 -0.034499  0.013993
6 -0.701870 -0.472082 -1.361445

Calling fillna with a dict, you can use a different fill value for each column:

In [16]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -1.253882  0.500000  0.000000
1  1.244064  0.500000  0.000000
2 -0.190684  0.500000 -0.334609
3  0.338836  0.500000 -0.573983
4 -0.667814 -0.257970 -0.049162
5 -0.096871 -0.034499  0.013993
6 -0.701870 -0.472082 -1.361445

In [18]:
df = pd.DataFrame(np.random.randn(7, 3))

df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0         1         2
0  0.593049 -0.071109  0.123373
1 -0.285702  0.564195 -0.861864
2 -1.505669       NaN -0.484560
3  2.170840       NaN  0.057625
4  0.883036       NaN       NaN
5  0.544782       NaN       NaN
6  1.972836       NaN       NaN

In [19]:
df.fillna(method='ffill')

0         1         2
0  0.593049 -0.071109  0.123373
1 -0.285702  0.564195 -0.861864
2 -1.505669  0.564195 -0.484560
3  2.170840  0.564195  0.057625
4  0.883036  0.564195  0.057625
5  0.544782  0.564195  0.057625
6  1.972836  0.564195  0.057625

In [20]:
df.fillna(method='ffill', limit=2)

0         1         2
0  0.593049 -0.071109  0.123373
1 -0.285702  0.564195 -0.861864
2 -1.505669  0.564195 -0.484560
3  2.170840  0.564195  0.057625
4  0.883036       NaN  0.057625
5  0.544782       NaN  0.057625
6  1.972836       NaN       NaN

# Data Transformation

### Removing Duplicates

In [27]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [28]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [29]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [30]:
data.drop_duplicates(['k1'])

k1  k2
0  one   1
1  two   1

In [31]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
6  two   4

### Transforming Data Using a Function or Mapping

In [32]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon',
                             'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [33]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

lowercased = data['food'].str.lower()

data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

We can also pass a function to do all of the work:

In [34]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### Renaming Axis Indexes

In [35]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), index=['Ohio', 'Colorado', 'New York'],
                   columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

Like a Series, the acis indeces have a map method.

In [39]:
transform = lambda x: x[:4].upper()

data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [44]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [46]:
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

Should you wish to modify a dataset in-place, pass inplace=True:

In [47]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

### Discretization and Binning

In [49]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

bins = [18, 25, 35, 60, 100]

cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [50]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [51]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [52]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

A parenthesis means that the side is open, while the square bracket means it is closed. You can change which side is closed by passing right=False.

In [53]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

You can pass your own bin names by passing a list or array to the labels option:

In [55]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

If you pass an integer number of bins to but instead of explicit bin edges, it will compute equal-length bins based on the minimum and maximum values in the data.

In [56]:
data = np.random.rand(20)

pd.cut(data, 4, precision=2)

[(0.76, 0.99], (0.073, 0.3], (0.53, 0.76], (0.76, 0.99], (0.073, 0.3], ..., (0.3, 0.53], (0.53, 0.76], (0.073, 0.3], (0.53, 0.76], (0.073, 0.3]]
Length: 20
Categories (4, interval[float64]): [(0.073, 0.3] < (0.3, 0.53] < (0.53, 0.76] < (0.76, 0.99]]

Similar to cut, you can pass your own quantiles:

In [57]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(0.783, 0.991], (0.0725, 0.0962], (0.457, 0.783], (0.783, 0.991], (0.0962, 0.457], ..., (0.457, 0.783], (0.457, 0.783], (0.0962, 0.457], (0.457, 0.783], (0.0725, 0.0962]]
Length: 20
Categories (4, interval[float64]): [(0.0725, 0.0962] < (0.0962, 0.457] < (0.457, 0.783] < (0.783, 0.991]]

### Detecting and Filtering Outliers

In [69]:
data = pd.DataFrame(np.random.randn(1000, 4))

data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.033136    -0.033452    -0.022614    -0.042953
std       1.047410     1.015449     1.027308     1.009763
min      -3.038030    -3.144667    -3.301015    -3.100436
25%      -0.701922    -0.727013    -0.723016    -0.717945
50%       0.029152    -0.066350    -0.029200    -0.022548
75%       0.760068     0.646126     0.627079     0.616234
max       3.413668     3.218935     3.401811     3.113114

In [70]:
col = data[2]

col[np.abs(col) > 3]

234   -3.301015
401    3.239278
537    3.012642
600    3.401811
Name: 2, dtype: float64

In [75]:
data[(np.abs(data) > 3.3).any(1)]

0         1         2         3
234 -1.158483 -0.773334 -3.301015  0.603254
260  3.375776  1.473571  0.023564 -0.420688
600 -1.074785 -2.069668  3.401811 -0.549551
812  3.413668 -1.731737  0.272459  0.610538

The statement np.sign(data) produces 1 and -1 values based on whether the values in the data are positive or negative:

In [76]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0  1.0 -1.0
1 -1.0  1.0 -1.0  1.0
2  1.0 -1.0  1.0 -1.0
3  1.0  1.0 -1.0  1.0
4 -1.0 -1.0 -1.0 -1.0

### Permutation and Random Sampling

In [79]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [80]:
sampler = np.random.permutation(5)
sampler

array([1, 4, 3, 2, 0])

This array can then be used in iloc-based indexing or the equivalent take function:

In [81]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
4  16  17  18  19
3  12  13  14  15
2   8   9  10  11
0   0   1   2   3

To select a random subset without replacement, you can use the sample method.<br>
To generate a sample with replacement, pass replace=True to sample.

In [84]:
df.sample(n=3)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
4  16  17  18  19

### Computing Indicator/Dummy Variables

In [86]:
df = pd.DataFrame({'key1': ['b', 'b', 'a', 'c', 'a', 'b'],
                  'data': range(6)})

pd.get_dummies(df['key1'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [88]:
dummies = pd.get_dummies(df['key1'], prefix='key')

df_with_dummy = df[['data']].join(dummies)
df_with_dummy

data  key_a  key_b  key_c
0     0      0      1      0
1     1      0      1      0
2     2      1      0      0
3     3      0      0      1
4     4      1      0      0
5     5      0      1      0

If a row in a DataFrame belongs to multiple categories, things are a bit more complicated:

In [92]:
names = ['movie_id', 'title', 'genres']

movies = pd.read_table('datasets/movielens/movies.dat', sep='::', header=None, names=names)
movies[:5]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [94]:
all_genres = []

for x in movies.genres:
    all_genres.extend(x.split('|'))
    
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [96]:
zero_matrix = np.zeros((len(movies), len(genres)))

dummies = pd.DataFrame(zero_matrix, columns=genres)

gen = movies.genres[0]

gen.split('|')

['Animation', "Children's", 'Comedy']

In [99]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [101]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1
    
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.head()

movie_id                               title                        genres  \
0         1                    Toy Story (1995)   Animation|Children's|Comedy   
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy   
2         3             Grumpier Old Men (1995)                Comedy|Romance   
3         4            Waiting to Exhale (1995)                  Comedy|Drama   
4         5  Father of the Bride Part II (1995)                        Comedy   

   Genre_Animation  Genre_Children's  Genre_Comedy  Genre_Adventure  \
0              1.0               1.0           1.0              0.0   
1              0.0               1.0           0.0              1.0   
2              0.0               0.0           1.0              0.0   
3              0.0               0.0           1.0              0.0   
4              0.0               0.0           1.0              0.0   

   Genre_Fantasy  Genre_Romance  Genre_Drama  ...  Genre_Crime  \
0            0.0            0.0          0.0  ...          0.0   
1            1.0            0.0          0.0  ...          0.0   
2            0.0            1.0          0.0  ...          0.0   
3            0.0            0.0          1.0  ...          0.0   
4            0.0            0.0          0.0  ...          0.0   

   Genre_Thriller  Genre_Horror  Genre_Sci-Fi  Genre_Documentary  Genre_War  \
0             0.0           0.0           0.0                0.0        0.0   
1             0.0           0.0           0.0                0.0        0.0   
2             0.0           0.0           0.0                0.0        0.0   
3             0.0           0.0           0.0                0.0        0.0   
4             0.0           0.0           0.0                0.0        0.0   

   Genre_Musical  Genre_Mystery  Genre_Film-Noir  Genre_Western  
0            0.0            0.0              0.0            0.0  
1            0.0            0.0              0.0            0.0  
2            0.0            0.0              0.0            0.0  
3            0.0            0.0              0.0            0.0  
4            0.0            0.0              0.0            0.0  

[5 rows x 21 columns]

A useful recipe for statistical applications is to combine get_dummies with a discretization function like cut:

In [103]:
np.random.seed(12345)

values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [105]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

pd.get_dummies(pd.cut(values, bins)).head()

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0

# String Manipulation

In [106]:
val = 'a,b,  guido'

val.split(',')

['a', 'b', '  guido']

split is often combined with strip to trim whitespace (including line breaks):

In [107]:
[x.strip() for x in val.split(',')]

['a', 'b', 'guido']

The difference between find and index is that index raises an exception if the string isn't found (versus returning -1):

In [108]:
val.index(',')

1

In [110]:
val.find(':')

-1

In [111]:
val.count(',')

2

In [112]:
val.replace(',', '::')

'a::b::  guido'

In [114]:
import re

text = 'foo    bar\t baz   \nquz'

re.split('\s+', text)

['foo', 'bar', 'baz', 'quz']

When you call re.split('\s+', text), the regular expression is first compiled, and then its split method is called on the passed text. You can compile the regex yourself with re.compile, forming a reusable regex object.

In [115]:
regex = re.compile('\s+')

regex.split(text)

['foo', 'bar', 'baz', 'quz']

If, instead, you wanted to get a list of all patterns matching the regex, you can use the finall method:

In [117]:
regex.findall(text)

['    ', '\t ', '   \n']

In [120]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

regex = re.compile(pattern, flags=re.IGNORECASE)

regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [121]:
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [122]:
text[m.start():m.end()]

'dave@google.com'

regex.match returns None if the pattern does not occur at the start of the string:

In [124]:
print(regex.match(text))

None


sub will return a new string with occurences of the pattern replaced by a new string:

In [125]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [126]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

regex = re.compile(pattern, flags=re.IGNORECASE)

regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

### Vectorized String Functions in pandas

In [128]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com', 'Rob': 'rob@gmail.com',
       'Wes': np.nan}

data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [129]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [130]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [131]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [132]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [133]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [134]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN